version: '3.5'
services:
  nginx:
    image: blog.returnnull.de/nginx:dev
    container_name: returnnull_nginx
    volumes:
      - ./../../code/public:/var/www/html/public
    ports:
      - '80:80'

  php:
    image: blog.returnnull.de/php:dev
    container_name: returnnull_php_fpm
    volumes:
      - ./../../code:/var/www/html

  database:
    image: blog.returnnull.de/database:dev
    container_name: returnnull_mysql
    volumes:
      - ./../../database:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'